name: custom_media_browser
description: "A Telegram-style custom file and image picker in Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.7.1
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  intl: ^0.20.2
  video_player: ^2.9.5
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  path: ^1.9.1
  open_filex: ^4.3.4
  photo_view: ^0.15.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
